name: build-and-release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        choco install visualstudio2017buildtools --version 15.9.28307.1238
        choco install visualstudio2017-workload-vctools
        choco install visualstudio2017-workload-manageddesktopbuildtools
        choco install wget

    - name: Setup LZ4 Library
      run: |
        wget https://github.com/lz4/lz4/archive/refs/tags/v1.9.3.zip -O lz4.zip
        unzip lz4.zip -d External/lz4
        mkdir -p External/lz4/dll
        cp External/lz4/lz4-1.9.3/dll/msys-lz4-1.dll External/lz4/dll/msys-lz4-1.dll
        cp External/lz4/lz4-1.9.3/dll/liblz4.dll.a External/lz4/dll/liblz4.dll.a

    - name: Build Solution
      run: |
        msbuild FrontEnd/MiSTerCast.sln /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v141

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MiSTerCast-Release
        path: FrontEnd/bin/Release/

    - name: Generate Release
      uses: softprops/action-gh-release@v1
      with:
        files: FrontEnd/bin/Release/MiSTerCast.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
